# Generated by Django 4.1.3 on 2023-03-01 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('57e3690a-f465-4ed4-99ed-b4b7f3a3b296'), editable=False),
        ),
    ]
