# Generated by Django 4.1.3 on 2023-03-02 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('d667c2e0-34b5-417d-9ac4-766a264b7d62'), editable=False, unique=True),
        ),
    ]
