# Generated by Django 4.1.3 on 2023-03-02 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
